{% set name = "microssim" %}
{% set version = "0.0.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/microssim/microssim-{{ version }}.tar.gz
  sha256: 460e1d9fa42ce3c8dd105b6450aa2f2a7a20a1e53ec24443b32bc5d73244ecdf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.21,<3.0.0
    - scipy <=1.17.0
    - scikit-image <=0.26.0
    - pytorch >=2.5,<=2.9.1
    - torchmetrics <=1.8.2
    - tqdm <=4.67.1

test:
  imports:
    - microssim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://careamics.github.io/microssim
  summary: Improved structural similarity metrics for comparing microscopy data.
  description: |
    Microssim is a library aimed at providing improved structural similarity metrics for comparing microscopy data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdeschamps
