{% set name = "microssim" %}
{% set version = "0.0.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/m/microssim/microssim-{{ version }}.tar.gz
  sha256: 1dcda02780a819cff4117a9254ab80d9416d16fe3f34fcb9334e6aa7c6025b4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.21,<3.0.0
    - scipy <=1.17.1
    - scikit-image <=0.26.0
    - pytorch >=2.5,<=2.14.0
    - torchmetrics <=1.8.2
    - tqdm <=4.70.0

test:
  imports:
    - microssim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://careamics.github.io/microssim
  summary: Improved structural similarity metrics for comparing microscopy data.
  description: |
    Microssim is a library aimed at providing improved structural similarity metrics for comparing microscopy data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdeschamps
